name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Format code
      run: |
        source venv/bin/activate
        make format

    - name: Lint code
      run: |
        source venv/bin/activate
        make lint

    - name: Run tests
      run: |
        source venv/bin/activate
        make test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/med-redact-llamafile:latest .

    - name: Push Docker image with retry
      run: |
        for i in {1..5}; do
          docker push ${{ secrets.DOCKER_USERNAME }}/med-redact-llamafile:latest && break || sleep 30
        done
